language: cpp

jobs:
  include:
    - os: osx
      osx_image: xcode10.3
      env: BITS_64=ON BITS_32=OFF CONFIGURATION_TYPE="Release" BUILD_NFIQ2_CLI=OFF CHECK_STYLE=OFF
      compiler: clang
    - os: osx
      osx_image: xcode9.4
      env: BITS_64=ON BITS_32=OFF CONFIGURATION_TYPE="Release" BUILD_NFIQ2_CLI=OFF CHECK_STYLE=OFF
      compiler: clang

addons:
  apt:
    packages:
      - libdb++-dev
      - libhwloc-dev
      - libjpeg-dev
      - libopenjp2-7-dev
      - libpng-dev
      - libsqlite3-dev
      - libssl-dev
      - libtiff-dev
      - zlib1g-dev
  homebrew:
    packages:
      - clang-format
      - berkeley-db
      - hwloc
      - jpeg-turbo
      - libpng
      - libtiff
      - openjpeg
      - openssl
      - sqlite
      - zlib

before_install:
    - |
      if [ "${CHECK_STYLE}" == "ON" ] ; then
          echo -n "Checking coding style with clang-format..."

          fail=0
          while read -r i; do
              if ! clang-format --Werror --dry-run "${i}" > /dev/null 2>&1;
              then
                  if [ "${fail}" == "0" ]; then
                      echo "[FAIL]"
                  fi
                  fail=1
                  echo "Please run clang-format -i ${i}"
              fi
          done < <(find NFIQ2 \( -name "*.c" -o -name "*.h" \
              -o -name "*.cpp" -o -name "*.hpp" \) -a \! -path '*wsq*' \
              -a \! -name 'RandomForestTrainedParams.h')

          if [ "${fail}" == "1" ]; then
              msg="Please run the above files through clang-format using the "
              msg+=".clang-format configuration and push your changes to the "
              msg+="same branch. See CONTRIBUTING.md for more information."
              echo "${msg}"
              exit 1
          else
              echo "[OKAY]"
          fi
      fi

before_script:
    - mkdir -p build
    - cd build
    - cmake -D32BITS=$BITS_32 -D64BITS=$BITS_64 -DCMAKE_BUILD_TYPE="$CONFIGURATION_TYPE" -DBUILD_NFIQ2_CLI=$BUILD_NFIQ2_CLI ..

script:
    - cmake --build .

cache:
  timeout: 1000
  directories:
    - $HOME/build/usnistgov/NFIQ2/build/OpenCV-prefix
    - $HOME/build/usnistgov/NFIQ2/build/fingerjetfxose
    - $HOME/build/usnistgov/NFIQ2/build/biomdi
    - $HOME/build/usnistgov/NFIQ2/build/libbiomeval-prefix
    - $HOME/Library/Caches/Homebrew

before_cache:
  - which brew && brew cleanup
